// Autoria Leo-Shiba GitHub
const { reagir, responderPV } = require('../core/utils');
module.exports = {
  nome: 'ajuda',
  aliases: ['help', 'menu'],
  descricao: 'Mostra todos os comandos disponíveis.',
  apenasAdmin: true,
  apenasGrupo: true,
  executar: async ({ sock, msg, autor }) => {
    await reagir(sock, msg, '✅');
    await responderPV(sock, autor, [
      '╔══════════════════════╗',
      '        🛡️ *MOD BOT*',
      '╚══════════════════════╝',
      '',
      '🔨 *Punições* _(admin)_',
      '├ !banir @membro',
      '├ !avisar @membro [motivo]',
      '├ !resetar @membro',
      '├ !silenciar @membro [min]',
      '└ !dessilenciar @membro',
      '',
      '👑 *Membros* _(admin)_',
      '├ !promover @membro',
      '└ !rebaixar @membro',
      '',
      '🔒 *Grupo* _(admin)_',
      '├ !trancar — só admins enviam',
      '└ !destrancar — todos podem enviar',
      '',
      '⚙️ *Configuração* _(admin)_',
      '├ !config — ver/alterar config',
      '├ !setboasvindas <msg>',
      '├ !setsaida <msg>',
      '└ !setregras <texto>',
      '',
      '🛠️ *Utilitários* _(admin)_',
      '├ !info — status do grupo',
      '├ !admins — listar admins',
      '├ !avisos [@membro] — ver avisos',
      '├ !ping — latência do bot',
      '├ !limpar [n] — apaga N msgs (padrão 10)',
      '├ !palavras — listar palavras proibidas',
      '├ !addpalavra <palavra>',
      '└ !rmpalavra <palavra>',
      '',
      '🌐 *Públicos*',
      '└ !regras — regras do grupo',
    ].join('\n'));
  }
};
